# PvPLogger config file
log-damage: true

# Outputs extra information into the console. (Warning: creates large files very quickly)
debug: false

# Outputs in the following formats: json
output-format: json
