name: PvPLogger
main: com.stefensharkey.pvplogger.PvPLogger
version: ${project.version}
author: Stefenatefun

commands:
  pvplogger:
    description: See PvPLogger help page.
    aliases: [pvpl]
    permission: pvplogger.help
  pvplogger reload:
    description: Reloads PvPLogger.
    aliases: [pvpr]
    permission: pvplogger.reload

permissions:
  pvplogger.*:
    description: Gives access to all PvPLogger permissions.
    children:
      pvplogger.reload: true
  pvplogger.reload:
    description: Reloads PvPLogger.
    default: op
